### ISSUE TITLE
Errors out of the box

### ISSUE THREAD

**Issue by gingerbeardman** [marianocarrazana/rouge#1]
With default setup and content i get errors:

<img width="1080" alt="Screen shot 2021-12-02 at 12 04 37" src="https://user-images.githubusercontent.com/49612/144418776-6c570d7a-dbe0-4697-baf0-f2f442cba53c.png">

**Comment by marianocarrazana** [comment]
Is the expected behavior, pages with no controllers display an error message with debug enabled(the home page doesnt have a controller).
You have two options: add a controller or disable the debug messages

**Comment by gingerbeardman** [comment]
OK thanks, it's not a good first experience.
